FROM python:3.10-slim

# set workdir
WORKDIR /app

# copy requirements & install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy rest of files
COPY . .

# expose port (Hugging Face expects 7860 by default)
EXPOSE 7860

# run FastAPI with uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]
